config/routes.rb
Taskitron::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end
  resources :tasks do
    member do
      post "stop", to: "tasks#stop"
      post "start", to: "tasks#start"
    end
  end
  resources :tags do
    collection do
      get '/:name', to: "tags#show", as: :name
      get '/:name/:day', to: 'tags#day', as: :day
    end
  end
  authenticated :user do
    root 'tasks#index', as: 'authenticated_root'
  end
  root 'welcome#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :task

  validates :name, :task_id, presence: true

  def days
    tasks.group_by { |t| t.created_at.to_date }.map { |date, tasks| date }.uniq
  end

  def tasks
    Task.joins(:tags).where('tags.name = ?', name)
  end

  def calculate_elapsed_time(tasks)
    tasks.map(&:elapsed_time).inject { |sum, t| sum += t } || 0
  end

  def elapsed_time
    calculate_elapsed_time(tasks)
  end

  def elapsed_time_by_day(date)
    calculate_elapsed_time(tasks.by_day(date))
  end

  def self.popular_by_user_id(user_id)
    Tag.joins(:task).where('tasks.user_id = ?', user_id).group('tags.name').order('count_name DESC').count('name')
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :timers, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :name, :user_id, presence: true
  validates :name, length: { in: 3..140 }

  scope :reverse, -> { order('created_at DESC') }
  scope :by_day, -> (date) { where(created_at: date.beginning_of_day..date.end_of_day) }

  self.per_page = 10

  def elapsed_time
    timers.completed.map(&:elapsed_time).inject { |time, sum| sum += time } || 0
  end

  def start
    timer.start
    timer.save
  end

  def stop
    current_timer = timer
    current_timer.stop
    current_timer.save
  end

  def completed?
    previous_timer = timers.last
    timer.new_record? && previous_timer.present?
  end

  def timer
    previous_timer = timers.last
    previous_timer.nil? || previous_timer.completed? ? timers.build : previous_timer
  end

  def parse_tags
    Tag.create(name.split('#').drop(1).map { |x| x[/\w+/] }.map { |tag| { task_id: id, name: tag.delete('#') } })
  end

  def hashtags
    tags.pluck(:name).map { |t| "##{t}" }
  end
end

app/models/timer.rb
class Timer < ActiveRecord::Base
  belongs_to :task, touch: true

  validates :task_id, presence: true

  scope :completed, -> { where("stopped_at IS NOT NULL") }

  def start
    self.started_at = Time.now
  end

  def stop
    self.stopped_at = Time.now
  end

  def started?
    started_at.present?
  end

  def stopped?
    stopped_at.present?
  end

  def completed?
    started? && stopped?
  end

  def elapsed_time
    completed? ? stopped_at - started_at : 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy

  def tags
    Tag.where(task_id: [tasks.pluck(:id)])
  end

  def popular_tags
    Tag.popular_by_user_id(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_timezone

  def set_timezone
    min = cookies[:timezone].to_i
    Time.zone = ActiveSupport::TimeZone[-min.minutes]
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def current_or_guest_user
    if current_user
      if session[:guest_user_id]
        logging_in
        guest_user.destroy
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  def guest_user
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  private

  def logging_in
    # For example:
    # guest_comments = guest_user.comments.all
    # guest_comments.each do |comment|
      # comment.user_id = current_user.id
      # comment.save!
    # end
  end

  def create_guest_user
    u = User.create(:name => "guest", :email => "guest_#{Time.now.to_i}#{rand(99)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :find_tags_by_name, only: [:show, :day]
  def index
    @tags = current_user.popular_tags
  end

  def show
    @tasks = @tag.tasks
    @elapsed_time = @tag.elapsed_time
  end

  def day
    begin
      date = Time.parse(params[:day])
    rescue
      raise ActionController::RoutingError.new('Not Found') || not_found
    end
    @tasks = @tag.tasks.by_day(date) || not_found
    @elapsed_time = @tag.elapsed_time_by_day(date) || not_found
  end

  protected

  def find_tags_by_name
    @tag = current_user.tags.find_by_name(params[:name]) || not_found
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :assign_variables, only: [:index, :create]

  def index
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      @task.start
      @task.parse_tags
      redirect_to authenticated_root_path
    else
      render :index
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to authenticated_root_path
  end

  def start
    @task = Task.find(params[:id])
    @task.start
    redirect_to authenticated_root_path
  end

  def stop
    @task = Task.find(params[:id])
    @task.stop
    redirect_to authenticated_root_path
  end

  protected

  def assign_variables
    @tasks = current_user.tasks.reverse.page(params[:page])
    @task = Task.new
    @tags = current_user.popular_tags
  end

  def task_params
    params.require(:task).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def format_elapsed_time(seconds)
    seconds = seconds.to_i
    days = seconds / 86400
    seconds -= days * 86400
    hours = seconds / 3600
    seconds -= hours * 3600
    minutes = seconds / 60
    seconds -= minutes * 60
    "#{days > 0 ? "#{pluralize(days, 'day')}," : ""} #{hours > 0 || days > 0 ? "#{pluralize(hours, 'hour')}," : ""} #{minutes > 0 || hours > 0 || days > 0 ? "#{pluralize(minutes, 'minute')}," : ""} #{seconds > 0 || minutes > 0 || hours > 0 || days > 0 ? pluralize(seconds, 'second') : "0 seconds"}".strip
  end

  def style_name(task)
    task.name.split.map { |s| task.hashtags.include?(s) ? content_tag(:a, href: "/tags/#{s.delete('#')}") { s } : s }.join(' ').html_safe
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Taskitron
    = stylesheet_link_tag "application", "data-turbolinks-track" => true
    link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"
    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"
    = csrf_meta_tags
  body
    nav.top-bar data-topbar=""
      ul.title-area
        li.name
          h1
            a href="/" Taskitron
        li.toggle-topbar.menu-icon
          a href="#"
            span
      section.top-bar-section
        ul.right
          - if current_user
            li= link_to "Tags", tags_path
            li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            li= link_to "Sign In", sign_in_path
            li= link_to "Sign Up", sign_up_path

    .row
      .small-12.columns
        .row
          .small-12.large-6.large-centered.columns
            p.alert.text-center= alert
        == yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/layouts/welcome.slim
doctype html
html
  head
    title Taskitron
    = stylesheet_link_tag "application", "data-turbolinks-track" => true
    link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"
    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"
    = csrf_meta_tags
  body
    nav.top-bar data-topbar=""
      ul.title-area
        li.name
          h1
            a href="/" Taskitron
        li.toggle-topbar.menu-icon
          a href="#"
            span
      section.top-bar-section
        ul.right
          - if current_user
            li= link_to "Tags", tags_path
            li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            li= link_to "Sign In", sign_in_path
            li= link_to "Sign Up", sign_up_path

    == yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/tags/_index.slim
ul.no-bullet
  - tags.each do |tag|
    li
      a href="/tags/#{tag[0]}"= tag[0]

app/views/tags/_show.slim
.row
  .small-12.large-6.large-centered.columns
    h2= "##{tag.name}"
    dl.sub-nav
      dd class="#{params[:day] ? '' : 'active'}"= link_to 'All Time', name_tags_path(tag.name)
      - @tag.days.each do |day|
        dd class="#{day.to_s == params[:day].to_s ? 'active' : ''}"= link_to day.strftime('%b %d %Y'), day_tags_path(tag.name, day)
    h3.subheader= format_elapsed_time(elapsed_time)
    .tasks
      = render partial: 'tasks/index', locals: { tasks: tasks }

app/views/tags/day.slim
= render partial: 'show', locals: { tag: @tag, tasks: @tasks, elapsed_time: @elapsed_time }

app/views/tags/index.slim
.row
  .small-12.large-6.large-centered.columns
    = render partial: 'index', locals: { tags: @tags }

app/views/tags/show.slim
= render partial: 'show', locals: { tag: @tag, tasks: @tasks, elapsed_time: @elapsed_time }

app/views/tasks/_index.slim
.tasks
  - tasks.group_by { |t| t.created_at.to_date }.each do |date, tasks|
    h3.task-group-heading
      = date.strftime('%b %d %Y')
      ul.tasks.no-bullet
        - tasks.each do |task|
          - cache(task) do
            li= render partial: 'tasks/show', locals: { task: task }

app/views/tasks/_show.slim
.task class="#{task.completed? ? '' : 'started'}" data-elapsed-time="#{task.elapsed_time}"
  .header
    - if task.completed?
      h6.subheader.right= format_elapsed_time(task.elapsed_time)
      .clearfix
    h5.name= style_name(task)
  .footer
    ul.inline-list.right
      - if task.completed?
        li
          = link_to start_task_path(task), method: :post, class: "start" do
            i.fa.fa-play-circle&nbsp;Start
      - else
        li
          = link_to stop_task_path(task), method: :post, class: "stop" do
            i.fa.fa-stop&nbsp;Stop
      li
        = link_to task, method: :delete do
          i.fa.fa-trash-o&nbsp;Delete
    .clearfix

app/views/tasks/index.slim
.row
  .small-12.large-6.large-offset-3.columns
    = form_for @task do |f|
      #new-task-content contenteditable="true" data-placeholder="Start something new"
      = f.text_area :name, class: "hide"
      = f.submit "Start", class: "button small right radius"
      .clearfix

    = render partial: 'tasks/index', locals: { tasks: @tasks }

    = will_paginate @tasks, page_links: false, next_label: "Older", previous_label: "Newer", class: "pagination-centered"

app/views/welcome/index.slim
section#hero
  .row
    .medium-7.large-6.columns
      h1 Taskitron
      h3
        | The best way to
        br.hide-for-small
        |  track your time
      br

  .row
    .medium-6.large-4.columns
      = link_to 'Get Started', sign_up_path, class: 'large button radius hide-for-small'
      = link_to 'Get Started', sign_up_path, class: 'small button show-for-small'

  .screenshot
    = image_tag asset_path('desktop.png'), data: { interchange: "[#{asset_path('mobile.png')}, (default)], [#{asset_path('tablet.png')}, (medium)], [#{asset_path('desktop.png')}, (large)]" }

section#main
  .row.text-center
    .medium-4.columns
      i.fa.fa-play-circle-o
      h4 Create
      p
        |
          Some things take longer than a
          pomodoro.
          Start and pause tasks until they're
          totally done.
    .medium-4.columns
      i.fa.fa-tags
      h4 Organize
      p
        |
          Use hashtags to keep track of which
          time is going to which project.
          View your tasks by day and by tag.

    .medium-4.columns
      i.fa.fa-bar-chart-o
      h4 Analyze
      p
        |
          View your total time by tag and
          by day.